spring:
  application:
    name: logant86
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/for_spring?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.1          
server:
  port: 8070