spring:
  application:
    name: logant86
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/TraningSpringBoot  
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver          

    # Hikari connection pool settings
    hikari:
      maximum-pool-size: 10                            # Maximum number of connections in the pool
      minimum-idle: 2                                  # Minimum number of idle connections
      idle-timeout: 60000                              # Idle timeout in milliseconds
      connection-timeout: 30000                        # Connection timeout in milliseconds

  jpa:
    hibernate:
      ddl-auto: update                                 # Automatically update the database schema
    show-sql: true                                     # Show SQL queries in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Specify PostgreSQL dialect
server:
  port: 8070