spring:
  application:
    name: logant86
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/TraningSpringBoot  
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver          

  jpa:
    hibernate:
      ddl-auto: update                                 
    show-sql: true                                     
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
  security:
    debug: true
    user:
      name: aungChay
      password: admin
server:
  port: 8070